
version: '2'

services:
  upsinfo:
    image: upsinfo:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 ./bin/www
